# Deploy Webserver
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache-hypertube
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: apache-hypertube
  template:
    metadata:
      labels:
        app: apache-hypertube
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - image: git.harknet.ml:5005/becrespi/hypertube/apache2:_VERSION_
        name: apache-hypertube 
        ports:
        - containerPort: 80
        env:
          - name: API_DOMAIN_NAME
            value: _API_DOMAIN_NAME_
          - name: FRONT_DOMAIN_NAME
            value: _FRONT_DOMAIN_NAME_
        tty: true
        volumeMounts: 
        - mountPath: /var/www/html/movies
          name: apache-hypertube-claim0
        - mountPath: /var/www/html/pictures
          name: apache-hypertube-claim1
      restartPolicy: Always
      volumes:
        - name: apache-hypertube-claim0
          persistentVolumeClaim:
            claimName: apache-hypertube-claim0
        - name: apache-hypertube-claim1
          persistentVolumeClaim:
            claimName: apache-hypertube-claim1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    volumeClaim: apache-hypertube-claim0
  name:  apache-hypertube-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    volumeClaim: apache-hypertube-claim1
  name:  apache-hypertube-claim1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
--- 
kind: Service
apiVersion: v1
metadata:
  name: apache-hypertube
spec:
  selector:
    app: apache-hypertube
  type: NodePort
  ports: 
  - port: 80
    nodePort: 30042